#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 28 00:17:06 2018

@author: Ethan Cheng
"""
%load_ext autoreload
%autoreload 2
from modules.laneProcPipe import laneProcessPipeline

#%%
params = {
        'calibPath' : 'camera_cal',
        'imgPath'   : 'test_images',
        'outPath' : 'output_images',
        'HLS_select' : 2, # pick saturation
        'HLS_cut' : [90, 255],
        'gradx_cut': [20, 100],
        'rows': 720,
        'cols': 1280,       
        } 
        
lpp = laneProcessPipeline(params)
lpp.calib()
#imshow(self.imgCalibOut)
#%%
lpp.test_perspetive_transform()
